[package]
name = "wf-main"
version = { workspace = true }
edition = { workspace = true }

[dependencies]
wf-token = { workspace = true }
wf-parse = { workspace = true }
clap = { workspace = true }
serde_json = { workspace = true }
