title: Wolf Scripting Language
description: An expression-based declarative scripting language
baseurl: ""
url: "https://wolf.phfox.net/"

personal_name: "Daniel P H Fox"
personal_url: "https://phfox.net"

copyright: Text is MIT licensed unless specified; use with attribution, links are appreciated.

plugins:
  - jekyll-feed
  - jekyll-seo-tag 